### ISSUE TITLE
Integrate with Continuous Integration service

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5-dev-bundler-rollup#33]
https://github.com/ckeditor/ckeditor5-dev-tests is fully integrated with Travis. This package can also have the integration.

We need to create a `.travis.yml` file:

```yml
language: node_js
node_js:
  - "6"
cache:
  - node_modules
install:
  - npm install
  - npm install codeclimate-test-reporter
script:
  - npm run coverage
after_success:
  - node_modules/.bin/codeclimate-test-reporter < coverage/lcov.info
```

And add 3 new badges in README in order:

1.  NPM 
2. Build (new) 
3. Coverage (new)
4. Code Climate (new)
5. Deps
6. Dev-deps
